name: Block dev version on main

on:
  pull_request:
    branches: [main]

jobs:
  check-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Install packaging and yaml libraries
        run: pip install packaging pyyaml

      - name: Verify version is a release build
        run: python .github/scripts/check_rel_version.py JobAppTracker/constants.py

      - name: Verify logs are set to the desired release configuration
        run: python .github/scripts/check_log_level.py log_config.yml
